---
title: "group1_HMO"
author: "Mo"
date: "`r Sys.Date()`"
output: html_document
---

```{r LoadingLibraries}
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("ggplotly")) install.packages("plotly")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("treemapify")) install.packages("treemapify")
listOfPackages <- c("tidyverse", "ggplot2", "treemapify", "hexbin", "RColorBrewer", "caret", "plotly")
lapply(listOfPackages, require, character.only = TRUE)
```

```{r}
# install.packages("ggfortify")
library("ggplot2")
library("dplyr")
library("ggfortify")
```


```{r ReadingData}
df <- read_csv('https://intro-datascience.s3.us-east-2.amazonaws.com/HMO_data.csv')
```

```{r ColumnsInDataset}
colnames(df)
```
```{r}
hmoData <- select(df,-X) # X is a unique identifier for each row. We wouldn't need it in our analysis
```

```{r CheckingForNullValues}
sum(is.na(hmoData)) # 158 null values
```

```{r CheckingForNullValues2}
# Checking each columns for number of nulls
colSums(is.na(hmoData))
# we can see that we have 78 nulls in bmi and 80 nulls in hypertension.
```

```{r Summary_hmoData$bmi}
summary(hmoData$bmi)
```

```{r MissingValuesInterpolation-BMI}
#There are null values in bmi and hypertension columns. These columns will be interpolated to fill the missing values.

hmoData$bmi <- imputeTS::na_interpolation(hmoData$bmi)
if(!sum(is.na(hmoData$bmi))) cat("BMI interpolated")
```

```{r}
table(hmoData$hypertension)
```

```{r MissingValuesInterpolation-Hypertension}
# Since we know that we have many missing values in BMI, lets clean them.
hmoData$hypertension <- imputeTS::na_interpolation(hmoData$hypertension)
if(!sum(is.na(hmoData$hypertension))) cat("Hypertension interpolated")
```

```{r}
table(hmoData$hypertension)
```

```{r}
hmoData$hypertension <- as.integer(hmoData$hypertension)
hist(hmoData$hypertension, breaks= 2)
```


```{r AgeAnalysis}
#Creating a histogram for the age
hist(hmoData$age, breaks= 20)
#we can observe that the hmoData is non-uniform as there are lot of people with age below 20.
```

```{r AgeAnalysis2}
# Checking for outliers for age
boxplot(hmoData$age) # not clear outliers
```

```{r}
violin_ageBmi <- ggplot(hmoData, aes(age,bmi))
violin_ageBmi<-  violin_ageBmi + geom_violin() + labs(title="Age - BMI distribution",
       subtitle="From the plot, we can see that BMI distribution is maximum around 30\nApproximamtely 42yo's have the least and highest BMI",
       caption="HMO Data",
       x="Age",
       y="BMI")
violin_ageBmi
```

```{r AgeAnalysisVScost}
# checking for a correlation b/w age and cost
hmoData %>% ggplot() +
  aes(x=age, y=cost) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE) +
  ggtitle("Age vs Cost")
```


```{r BMIAnalysis-Outliers}
# checking for outliers
boxplot(hmoData$bmi) # not clear outliers
```

```{r ComputingQuartilesForIdentifyingOutliers}
quartiles <- quantile(hmoData$bmi, probs=c(.25, .75), na.rm = FALSE)
IQR <- IQR(hmoData$bmi)
Lower <- quartiles[1] - 1.5*IQR
Upper <- quartiles[2] + 1.5*IQR
```

```{r}
hmoData <- subset(hmoData, hmoData$bmi > Lower & hmoData$bmi <= Upper-1)
```

```{r}
boxplot(hmoData$bmi) # not more outliers
```
```{r BMIAnalysis}
hist(hmoData$bmi, breaks= 20)
```

```{r CorrelationBMIvCost}
# checking for a corelation b/w bmi and cost
hmoData %>% ggplot() +
  aes(x=bmi, y=cost) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE) +
  ggtitle("BMI vs Cost")
```

```{r}
hmoData %>% ggplot() +
  geom_bin2d(mapping = aes(x = bmi, y = cost))

# install.packages("hexbin")
hmoData %>% ggplot() +
  geom_hex(mapping = aes(x = bmi, y = cost))
```

```{r}
hmoData %>% ggplot(aes(x = bmi, y = cost)) + 
  geom_boxplot(mapping = aes(group = cut_width(bmi, 0.1)))
```


```{r NumberOfChildren}
hist(hmoData$children, breaks=5)
```

```{r NumberOfChildren-Outliers}
boxplot(hmoData$children) # no outliers
```

```{r CorrelationNumberOfChildrenvsCost}
# checking for a correlation b/w children and cost
hmoData %>% ggplot() +
  aes(x=children, y=cost) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE) +
  ggtitle("Number of children vs Cost")
```

```{r}
# The following columns can be converted into categorical hmoData.
unique(hmoData$location)
# cost_location <- hmoData %>% group_by(location) %>% summarise(Avg_Cost = mean(cost))
# barplot(cost_location$Avg_Cost)
```

```{r}
cost_smoker <- hmoData %>% group_by(smoker) %>% summarise(Avg_Cost = mean(cost))
barplot(cost_smoker$Avg_Cost)
summary(hmoData$cost[hmoData$smoker =="yes"])
summary(hmoData$cost[hmoData$smoker =="no"])
```


```{r}
summary(hmoData$cost[hmoData$location_type =="Urban"])
summary(hmoData$cost[hmoData$location_type =="Country"])
```

```{r}
summary(hmoData$cost[hmoData$yearly_physical =="No"])
summary(hmoData$cost[hmoData$yearly_physical =="Yes"])
```

```{r}
summary(hmoData$cost[hmoData$exercise =="Active"])
summary(hmoData$cost[hmoData$exercise =="Not-Active"])
```

```{r}
summary(hmoData$cost[hmoData$married =="Married"])
summary(hmoData$cost[hmoData$married =="Not_Married"])
```

```{r}
summary(hmoData$cost[hmoData$gender =="male"])
summary(hmoData$cost[hmoData$gender =="female"])
```

```{r HypertensionPieChart}
pie(table(hmoData$hypertension), labels = c('Without Hypertension', 'With hypertension'))

```

```{r}
sum(hmoData$hypertension > 0 & hmoData$hypertension < 1)
```

```{r}
summary(hmoData$cost)
```

```{r}
hist(hmoData$cost, breaks = 20)
```

```{r}
boxplot( hmoData$cost, hmoData = hmoData)
```

```{r}
mapDF <- hmoData %>% group_by(location) %>% summarise(mean(cost))
```

```{r}
us <- map_data("state")
us$state_name <- tolower(us$region)
coord <- data.frame(loc=tolower(mapDF$location),avg_cost=mapDF$`mean(cost)`)
mergedDF <- merge(us,coord, by.x='state_name',by.y='loc')
mergedDF <- mergedDF %>% arrange(order)

```

```{r}
mergedDF %>% ggplot(aes(map_id= region)) + 
  geom_polygon(color="black",aes(x=long,y=lat,group=group,fill=avg_cost))  +
  expand_limits(x=mergedDF$long, y=mergedDF$lat)+
  coord_map("mercator") +
  ggtitle("Mean Cost for Each Location")
```

```{r}

```



```{r Treemap}
# library(treemapify)
# ageCat_treemap <- ggplot(hmoData, aes(area = hmoData$age, fill = hmoData$cost))
# ageCat_treemap <- ageCat_treemap + geom_treemap()
# ageCat_treemap
```

```{r Hexbin}

# bin<-hexbin(hmoData$exercise, hmoData$cost)
# my_colors=colorRampPalette(rev(brewer.pal(11,'Spectral')))
# plot(bin, main="" , colramp=my_colors , legend=F )


```


```{r}
unique(hmoData$location)
hmoData$location <- as.factor(hmoData$location)
```

```{r DataPrepForModelTraining}
prepare_data_for_model <- function(df){
  cat("Preparing dataframe for fitting the model....")
  cat("\nRenaming the columns. Current column names are : \n",colnames(df), "\n")
  df<-
    df %>%
    rename(isSmoker = smoker
           ,gender_isMale = gender
           ,exercise_isActive = exercise
           ,location_typeIsUrban = location_type)
  cat("\nAfter renaming : ",colnames(df))
  # df$isSmoker <- as.integer(df$isSmoker)
  df$married <- as.integer(ifelse(df$married == "Married", 1, 0))
  df$gender_isMale <- as.integer(ifelse(df$gender_isMale == "male", 1, 0))
  df$exercise_isActive <- as.integer(ifelse(df$exercise_isActive == "Active", 1, 0))
  df$location_typeIsUrban <- as.integer(ifelse(df$location_typeIsUrban == "Urban", 1, 0))
  df$isSmoker <- as.integer(ifelse(df$isSmoker == "yes", 1, 0))
  df$yearly_physical <- as.integer(ifelse(df$yearly_physical == "Yes", 1, 0))
  df$Age_Category <- NA
  df <- mutate(df, Age_Category = ifelse(age %in% 0:21, "Young Adults"
                                          ,ifelse(age %in% 21:36, "Adults"
                                          ,ifelse(age %in% 36:51, "Middle Aged Adults", "Old Aged Adults"))))
  return(df)
}
```

```{r}
updatedHMOdata <- prepare_data_for_model(hmoData)
updatedHMOdata
```


```{r}
# ageCategoryCount <- data.frame((table(hmoData$Age_Category)))
# table(hmoData$Age_Category)
# unique(hmoData$Age_Category)
```


```{r}
corr <- cor(updatedHMOdata[, unlist(lapply(updatedHMOdata, is.numeric))], use = "complete.obs")
heatmap(corr, Colv = NA, Rowv = NA)
```

```{r DataPrepForModelTraining}
factorizing_data_for_model <- function(df){
  cat("Preparing dataframe for fitting the model....")
  df$isSmoker<-as.factor(df$isSmoker)
  df$location_typeIsUrban<-as.factor(df$location_typeIsUrban)
  df$exercise_isActive<- as.factor(df$exercise_isActive)
  df$married<-as.factor(df$married)
  df$gender_isMale<-as.factor(df$gender_isMale)
  df$yearly_physical<-as.factor(df$yearly_physical)
  df$hypertension<-as.factor(df$hypertension)
  return(df)
}
```

```{r VariableFactorizatino}
updatedHMOdata<-factorizing_data_for_model(updatedHMOdata)
```


```{r}
p <- updatedHMOdata %>%
  # filter(location_typeIsUrban==1) %>%
ggplot( aes(age, cost, color=bmi)) +
  geom_point() +
  theme_bw()
# p <- p +  scale_shape_manual(values = c(0,23))
ggplotly(p)

```

```{r}
p <- updatedHMOdata %>%
  # filter(location_typeIsUrban==1) %>%
ggplot( aes(age, cost, color=isSmoker)) +
  geom_point() +
  theme_bw()
p <- p +  scale_shape_manual(values = c(0,23))
ggplotly(p)
```

```{r CreateDataPartition}
summary(updatedHMOdata$cost)
str(updatedHMOdata)
```

```{r Regression Model}
lmOut <- lm(data = updatedHMOdata, cost ~ .)
summary(lmOut)
```

```{r}
save(lmOut, file ='../ist687_hmo/model_test')

```

```{r}
testDF<- data.frame(read_csv('../HMO_TEST_data_sample.csv'))
testDF <- prepare_data_for_model(testDF)
testDF <- factorizing_data_for_model(testDF)
testDF
```

```{r}
costPrediction <- predict(lmOut,testDF)
cat(costPrediction)
```

```{r}
# SVM
```

```{r}
quartiles <- quantile(updatedHMOdata$cost, probs=c(.25,.75), na.rm = FALSE)
IQR <- IQR(updatedHMOdata$cost)
Lower <- quartiles[1] - 1.5*IQR
Upper <- quartiles[2] + 1.5*IQR 
Lower
Upper
quartiles
```

```{r}
# updatedHMOdata <- subset(updatedHMOdata, cost >= Lower & cost <= Upper)
```

```{r}
median(updatedHMOdata$cost)
```

```{r}
updatedHMOdata$expensive <- as.factor(ifelse(updatedHMOdata$cost>Upper,TRUE,FALSE))
updatedHMOdata
```

```{r}
trainSet <- createDataPartition(y = updatedHMOdata$expensive , p= 0.7, list = FALSE)
trainData <- updatedHMOdata[trainSet,]
testData <- updatedHMOdata[-trainSet,]
ctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)
svmLinear <- train(expensive~age+bmi+children+isSmoker+yearly_physical+exercise_isActive+hypertension+married, data = trainData, method = "svmLinear",
                    trControl=ctrl, preProcess = c("center", "scale"), tuneLength = 10)
svmLinear
```

```{r}
#predict people for which healthcare would be expensive
head(testData)
predDF <- predict(svmLinear, newdata = testData)
predDF
```

```{r}
#using confusion matrix to check performance of model
confMatrix<-confusionMatrix(predDF, testData$expensive)
plot(confMatrix$table, color = c("cyan", "blue"), conf.level = 0, margin = 1, main = "Confusion Matrix")
confMatrix
```

```{r}
testDF<- data.frame(read_csv('../HMO_TEST_data_sample.csv'))
testDF <- prepare_data_for_model(testDF)
testDF <- factorizing_data_for_model(testDF)
testDF$cost <- costPrediction
testDF_y<- data.frame(read_csv('../HMO_TEST_data_sample_solution.csv'))
testDF_pred <- predict(svmLinear, newdata = testDF)
confMatrix<-confusionMatrix(testDF_pred, as.factor(testDF_y$expensive))
plot(confMatrix$table, color = c("cyan", "blue"), conf.level = 0, margin = 1, main = "Confusion Matrix")
confMatrix

```


```{r}
length(testDF_pred)
length(testDF_y$expensive)
# K-Means
```

```{r}
HMO_x <- updatedHMOdata[,names(updatedHMOdata) != "cost"]
HMO_x <- HMO_x[,names(HMO_x) != "expensive"]
HMO_x <- data.matrix(HMO_x)
```

```{r}
elbowPoint <- function(data, nc=15, seed=1234){
  data <- na.omit(data)
  wss <- (nrow(data)-1)*sum(apply(data,2,var))
  for (i in 2:nc){
    set.seed(seed)
    wss[i] <- sum(kmeans(data, centers=i)$withinss)}
  plot(1:nc, wss, type="b", xlab="Number of Clusters",
       ylab="Within groups sum of squares")
  wss
}
```

```{r}
elbowPoint(HMO_x[!is.na(HMO_x)])
str(HMO_x)
```

```{r}
k <- 3
dim(HMO_x)
```

```{r}
HMO_x <- na.omit(HMO_x)
kmean <- kmeans(HMO_x[!is.na(HMO_x)],k)
kmean$centers
```

```{r}
autoplot(kmean, HMO_x, frame = TRUE)
```
